# Generated by Django 6.1.1 on 2026-09-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(verbose_name=8)),
                ('description', models.CharField(verbose_name=255)),
                ('discount', models.FloatField()),
            ],
        ),
    ]
