# Generated by Django 6.1.1 on 2026-09-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_offer_code_alter_offer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
